// d:\flutter_projelerim\filmologyenidenblocson\filmolog\filmolog\lib\features\movie\search\data\models.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:


export 'search_multi_model.dart';
export 'search_people_model.dart';