// d:\flutter_projelerim\filmologyenidenblocson\filmolog\filmolog\lib\features\movie\people\presentation\pages.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:


