// d:\flutter_projelerim\filmologyenidenblocson\filmolog\filmolog\lib\features\movie\movie_list\data\datasources\remote.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:


export 'movie_list_remote.dart';