// d:\flutter_projelerim\filmologyenidenblocson\filmolog\filmolog\lib\features\movie\movies\presentation\widgets\recommendatiton_tab.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:


export 'movie_detail_reco.dart';