// d:\flutter_projelerim\filmologyenidenblocson\filmolog\filmolog\lib\features\movie\people\data\datasource\remote.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:


export 'people_remote.dart';