// d:\flutter_projelerim\filmologyenidenblocson\filmolog\filmolog\lib\features\movie\people\presentation\widget\movie_cast_tab.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:


export 'people_movies.dart';