// d:\flutter_projelerim\filmologyenidenblocson\filmolog\filmolog\lib\features\movie\search\domain\repositories.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:


export 'search_repository.dart';