// d:\flutter_projelerim\filmologyenidenblocson\filmolog\filmolog\lib\features\movie\search\data\datasources\remote.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:


export 'search_remote.dart';