// d:\flutter_projelerim\filmologyenidenblocson\filmolog\filmolog\lib\features\movie\search\data\datasources.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:

export 'remote/remote.dart';
export 'search_remote_datasource.dart';