// d:\flutter_projelerim\filmologyenidenblocson\filmolog\filmolog\lib\core\resources.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:


export 'color_manager.dart';
export 'font_manager.dart';
export 'route_constants.dart';
export 'theme_manager.dart';
export 'values_manager.dart';