// d:\flutter_projelerim\filmologyenidenblocson\filmolog\filmolog\lib\features\movie\collection\data\repositories.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:


export 'collection_repository_imp.dart';