// d:\flutter_projelerim\filmologyenidenblocson\filmolog\filmolog\lib\features\movie\movies\presentation\widgets\cast_and_crew_tab.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:


export 'movies_detail_about_cast_and_crew_widget.dart';
export 'movie_detail_cast_crew.dart';