// d:\flutter_projelerim\filmologyenidenblocson\filmolog\filmolog\lib\features\movie\people\data\model.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:


export 'people_model.dart';