// d:\flutter_projelerim\filmologyenidenblocson\filmolog\filmolog\lib\features\movie\discovery\data\repositories.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:


export 'discovery_repository_imp.dart';