// d:\flutter_projelerim\filmologyenidenblocson\filmolog\filmolog\lib\features\movie\movies\presentation\widgets\media_tab.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:


export 'movies_detail_images_poster_widget.dart';
export 'movies_detail_videos_widget.dart';
export 'movies_detai_images_backdrop_widget.dart';
export 'movie_detail_media.dart';