// d:\flutter_projelerim\filmologyenidenblocson\filmolog\filmolog\lib\features\movie\search\domain\entities.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:


export 'search_multi_entity.dart';
export 'search_people_entity.dart';