// d:\flutter_projelerim\filmologyenidenblocson\filmolog\filmolog\lib\features\movie\movie_list\domain\entities.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:


export 'movie_list_entity.dart';