// d:\flutter_projelerim\filmologyenidenblocson\filmolog\filmolog\lib\app\widgets.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:


export 'base_poster.dart';