// d:\flutter_projelerim\filmologyenidenblocson\filmolog\filmolog\lib\features\movie\movies\presentation\widgets.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:

export 'movies_about_tab/movies_about_tab.dart';
export 'movies_detail_stack_widget.dart';