// d:\flutter_projelerim\filmologyenidenblocson\filmolog\filmolog\lib\features\movie\movies\presentation\widgets.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:

export 'abouth_tab/abouth_tab.dart';
export 'cast_and_crew_tab/cast_and_crew_tab.dart';
export 'media_tab/media_tab.dart';
export 'movies_about_tab/movies_about_tab.dart';
export 'recommendatiton_tab/recommendatiton_tab.dart';
export 'similar_tab/similar_tab.dart';
export 'movies_detail_stack_widget.dart';