// d:\flutter_projelerim\filmologyenidenblocson\filmolog\filmolog\lib\features\movie\movies\presentation\widgets\abouth_tab.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:


export 'movies_about_tab_widget.dart';
export 'movie_detail_about.dart';