// d:\flutter_projelerim\filmologyenidenblocson\filmolog\filmolog\lib\features\movie\discovery\data\models.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:


export 'future_movies_model.dart';
export 'future_tv_discovery_model.dart';