// d:\flutter_projelerim\filmologyenidenblocson\filmolog\filmolog\lib\features\movie\movies\presentation\widgets\movies_about_tab.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:


export '../abouth_tab/movies_about_tab_widget.dart';
export '../cast_and_crew_tab/movies_detail_about_cast_and_crew_widget.dart';
export 'movies_detail_collection_widget.dart';
export 'movies_detail_overview_widget.dart';
export '../media_tab/movies_detail_videos_widget.dart';