// d:\flutter_projelerim\filmologyenidenblocson\filmolog\filmolog\lib\features\movie\movies\domain\repositories.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:


export 'movies_detail_repository.dart';