// d:\flutter_projelerim\filmologyenidenblocson\filmolog\filmolog\lib\features\movie\collection\presentation\bloc.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:


export 'collection_bloc.dart';