// d:\flutter_projelerim\filmologyenidenblocson\filmolog\filmolog\lib\features\movie\movie_list\data\repositories.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:


export 'movie_list_repository_imp.dart';